# Generated by Django 4.0 on 2022-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_image',
            field=models.ImageField(upload_to='jobs/images'),
        ),
    ]
