# Generated by Django 4.0 on 2022-02-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
