# Generated by Django 4.0 on 2022-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
