# Generated by Django 4.0 on 2022-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_company',
            field=models.CharField(default='pvt.ltd', max_length=30),
        ),
    ]
