# Generated by Django 4.0 on 2022-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_giver', models.CharField(max_length=30)),
                ('job_worker', models.CharField(max_length=30)),
            ],
        ),
    ]
