# Generated by Django 4.0 on 2022-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='job_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
