# Generated by Django 4.0 on 2022-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_history_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='job_amount',
            field=models.IntegerField(default=0),
        ),
    ]
