# Generated by Django 4.0.1 on 2022-03-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_deal_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobs.jobs', unique=True),
        ),
    ]
