# Generated by Django 4.0.1 on 2022-03-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_deal_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
