# Generated by Django 4.0.1 on 2022-01-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('pswd', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('gst', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
                ('uname', models.CharField(max_length=20)),
            ],
        ),
    ]
