# Generated by Django 4.0.1 on 2022-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('companyname', models.CharField(max_length=20)),
                ('ownername', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=20)),
                ('bio', models.TextField(max_length=80)),
                ('address', models.TextField(max_length=80)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
