# Generated by Django 4.0.1 on 2022-01-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0003_remove_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gst',
        ),
        migrations.AddField(
            model_name='profile',
            name='regis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginmodule.regis'),
        ),
    ]
