# Generated by Django 4.0.1 on 2022-01-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0004_remove_profile_contact_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='regis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='loginmodule.regis'),
        ),
    ]
