# Generated by Django 4.0.1 on 2022-01-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0005_alter_profile_regis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='regis',
            new_name='_regis',
        ),
    ]
