# Generated by Django 4.0.1 on 2022-01-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0007_remove_profile_id_alter_profile__regis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_regis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loginmodule.regis'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='none', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='none', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='companyname',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ownername',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='regis',
            name='uname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
