# Generated by Django 4.0.1 on 2022-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0008_alter_profile__regis_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='noffce', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='noffne', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='companyname',
            field=models.CharField(default='noffne', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ownername',
            field=models.CharField(default='noffne', max_length=20),
        ),
    ]
