# Generated by Django 4.0.1 on 2022-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0009_alter_profile_address_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis',
            name='uname',
            field=models.CharField(max_length=20),
        ),
    ]
