# Generated by Django 4.0 on 2022-02-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0011_rename__regis_profile_regis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='regis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loginmodule.regis'),
        ),
    ]
